### ISSUE TITLE
Rainloop set rights (to be able to change admin password)

### ISSUE THREAD

**Issue by dragonito** [lava/dockermail#20]
Hi,

if you can´t change the admin password in admin panel you have to check the rights.
```bash
cd /var/www/
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;

chown -R www-data:www-data .
```

perhaps it is possible to set the rights on docker build.

Cu

Robin

**Comment by lava** [comment]
Weird, I remember this working without having to do anything. Anyway, thanks for the info.

**Comment by dragonito** [comment]
I got this problem on normal unchanged configuration. Perhaps the rights has to be set a little bit later in script.

**Comment by alwinmark** [comment]
Hello!

 

You have a new message, please read <http://wakokubag.com/accusation.php?yhsqa>

 

a.karabiowski@gmx.net

**Comment by alwinmark** [comment]
Hello!

 

You have a new message, please read <http://gratefulexistence.com/fight.php?gd>

 

a.karabiowski@gmx.net
