### ISSUE TITLE
send email error

### ISSUE THREAD

**Issue by cphubs** [lava/dockermail#22]
Hi

I can recive email but can not send email to another domain like gmail or yahoo
previosly i can send email too!
I use rainloop

**Comment by lava** [comment]
Some big mail providers (e.g. web.de, don't know about yahoo) require some additional steps before they will whitelist mail from your server (usually writing an email to their webmaster is enough). So if possible it would probably be easier to investigate this by sending mails to a server that is known to be liberal in what it accepts, e.g. a friend's server or another instance of dockermail. That said, I've never had problems with gmail.

The relevant logs should be under `/var/log/mail.log` in the dovecot container. (Though docker seems to like breaking the way to read them every few versions without a good reason, so you might have to search around a bit for how to do it ;)

**Comment by cphubs** [comment]
I migrate from DO to Vultr.com and mail server is default blocked. I ticket and unblock it. 

Thank you
