### ISSUE TITLE
Dovecot image missing from docker.io

### ISSUE THREAD

**Issue by vfulco** [lava/dockermail#23]
Looks like no dovecot version as stated in the code on dockerhub.  Edited file for latest 2.2.19 and still no image available.  Breaks the entire install.

**Comment by lava** [comment]
I'm not sure what you mean by dockerhub? It's intended that you build the dovecot image by yourself, with the Dockerfile contained in the dovecot/ subdirectory.

**Comment by vfulco** [comment]
You are right.  My mistake after too long a day when this error surfaced. Thanks.


make run-all
docker run -d -p 0.0.0.0:25:25 -p 0.0.0.0:587:587 -p 0.0.0.0:143:143 -v /srv/vmail:/srv/vmail dovecot:2.2.19

Unable to find image 'dovecot:2.2.19' locally
Pulling repository docker.io/library/dovecot
Error: image library/dovecot:2.2.19 not found
Makefile:21: recipe for target 'run-dovecot' failed
make: *** [run-dovecot] Error 1

**Comment by lava** [comment]
Interesting...it's actually a bit concerning that you could have ended up with some random binary image by accident, if somebody else would have uploaded one called `dovecot`. If there's a way to disable this behaviour for the docker client, I'd be happy to accept a pull request.
