### ISSUE TITLE
Rainloop not working

### ISSUE THREAD

**Issue by Kiina** [lava/dockermail#26]
I tested this on different machines, so it seems like an Issue with the Dockerfile.

If you start the container you get an Page:

> Permission denied!
> 
> 
> RainLoop Webmail cannot access to the data folder "/var/www/html/data/" 

Which seems weird because the Dockerfile runs a chown on /var/www. But if you run a bash in the Container you see that the folder is still owned by root.

If you run the chown again you now get a page:

> Loading
> An Error occurred, 
> please refresh the page and try again.

**Comment by lava** [comment]
I wonder if it's caused by the recent move to rainloop 1.9.4

I havent used the webmail part for quite some time now, but maybe someone who has it up and running can check if the access rights for `/var/www/html/data` are correct with the older version?
